ALTER TYPE "public"."region" ADD VALUE 'uk';--> statement-breakpoint
ALTER TYPE "public"."region" ADD VALUE 'tw';--> statement-breakpoint
ALTER TYPE "public"."region" ADD VALUE 'hk';--> statement-breakpoint
ALTER TYPE "public"."region" ADD VALUE 'in';--> statement-breakpoint
ALTER TYPE "public"."region" ADD VALUE 'sg';--> statement-breakpoint
ALTER TYPE "public"."region" ADD VALUE 'apac';--> statement-breakpoint
ALTER TYPE "public"."region" ADD VALUE 'asia';--> statement-breakpoint
ALTER TYPE "public"."region" ADD VALUE 'emea';--> statement-breakpoint
ALTER TYPE "public"."region" ADD VALUE 'americas';--> statement-breakpoint
ALTER TYPE "public"."region" ADD VALUE 'latam';--> statement-breakpoint
ALTER TYPE "public"."region" ADD VALUE 'mena';--> statement-breakpoint
ALTER TYPE "public"."region" ADD VALUE 'anz';--> statement-breakpoint
ALTER TYPE "public"."region" ADD VALUE 'sea';--> statement-breakpoint
ALTER TYPE "public"."region" ADD VALUE 'oceania';--> statement-breakpoint
ALTER TYPE "public"."region" ADD VALUE 'africa';--> statement-breakpoint
ALTER TYPE "public"."region" ADD VALUE 'middle_east';--> statement-breakpoint
ALTER TABLE "reports" DROP COLUMN "region";--> statement-breakpoint
ALTER TABLE "reports" ADD COLUMN "regions" "public"."region"[];
